instance-id: ${instance_name}
local-hostname: ${instance_name}
network:
  version: 2
  ethernets:
    ens192:
      addresses:
        - ${network_address}
      gateway4: ${network_gateway}
      nameservers:
          addresses: [10.0.0.100, 10.0.0.101]
